#cloud-config 
package_upgrade: true
packages:
  - python3-pip #Dependency package for cur
runcmd:
   - curl -sSL https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/master/install.sh | sh - #Install cloud-init
power_state:
  timeout: 30
  mode: reboot